### PR TITLE
Switch from "teams" to "projects" to keep up with decoupling

### PR DESCRIPTION
**Pull request by chadwhitacre**
Part of https://github.com/gratipay/inside.gratipay.com/issues/432. Closes https://github.com/gratipay/inside.gratipay.com/issues/802.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
@mattbk Do you remember what the `team-approve.png` is for? 0bf83e09c1839032d2e7c473f544115b02e947f9 Do we still need it?

**Comment by mattbk** [comment]
It was supposed to go in the readme, but I think that particular PR got shot down. It was just an example image, probably better under IG.

**Comment by mattbk** [comment]
Changed title because I thought this might be about GitHub projects (e.g., https://github.com/gratipay/team-review/projects) and that we were going to be using that for the review process somehow.

**Comment by chadwhitacre** [comment]
> It was supposed to go in the readme, but I think that particular PR got shot down. It was just an example image, probably better under IG.

Okay, removed in 27382b3584ac3af6976a566cd41f8e9a27d251f5.

**Comment by chadwhitacre** [comment]
You good here, @mattbk?

**Comment by mattbk** [comment]
Yes. Are we ready to go?

**Comment by chadwhitacre** [comment]
> Are we ready to go?

Yes! Gonna drive from https://github.com/gratipay/gratipay.com/pull/4221 ...

**Pull request merged**
